Add provide privacy to BRI-1
eea-oasis/baseline pull request #299
Opened 2021-01-12 03:54 UTC by kthomas

# Description

Add Provide Privacy to BRI-1.

[Provide Privacy](https://docs.provide.services/privacy) is a golang-based microservice that delivers high performance by way of [gnark](https://github.com/ConsenSys/gnark).

This PR makes use of the `zkSnarkCircuitProviderServiceProvide` [privacy provider](https://github.com/ethereum-oasis/baseline/blob/master/core/privacy/src/zkp/provide.ts).

## Related Issue

https://community.provide.services/t/zkp-in-baseline-protocol/65

## Motivation and Context

Scalable ZKPs for production.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-07-06 02:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/eea-oasis/baseline?pullRequest=299) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/eea-oasis/baseline?pullRequest=299) before we can accept your contribution.<br/>**0** out of **4** committers have signed the CLA.<br/><br/>:x: kthomas<br/>:x: BrianCraig<br/>:x: j4ys0n<br/>:x: LucasRodriguez<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/eea-oasis/baseline?pullRequest=299) it.</sub>

2021-10-12 18:02 UTC, kthomas commented
Closing in favor of https://github.com/eea-oasis/baseline/pull/387

2021-11-09 00:45 UTC, LucasRodriguez approved these changes

2021-11-09 02:23 UTC, tkstanczak commented on examples/bri-1/base-example/test/e2e.spec.ts
> +        // describe('update a work step', () => {
are you sure you want to comment out the tests?

2021-11-09 02:24 UTC, tkstanczak requested changes
tests got commented out

2021-11-09 02:42 UTC, skarred14 approved these changes

2021-11-09 02:52 UTC, merged