Baseledger excel
eea-oasis/baseline pull request #444
Opened 2021-12-23 19:21 UTC by skosito

# Description

Baseledger Excel uses Baseledger Lakewood (https://lakewood.baseledger.net/) testnet and Baseledger's concept TrustMesh (https://docs.baseledger.net/baseledger-concepts/trustmesh) to sync 2 Excel files. This PR introduces excel file with VBA macros code and README file with quite detailed explanation of functionality and tutorial on how to use it.

## Related Issue

Not excel specific issue, but it is mentioned here https://github.com/eea-oasis/baseline-blips/issues/6.

## Motivation and Context

Please check https://github.com/eea-oasis/baseline-blips/issues/6.

## How Has This Been Tested

It demonstrates a happy path which was tested a lot manually during development.

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

Only core here is VBA, which doesn't have code style defined in this project. Also, there are not automated tests for VBA code.

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-12-23 19:29 UTC, ognjenkurtic approved these changes

2021-12-28 11:06 UTC, fosgate29 requested changes
LInk inside .xlsm https://baseledger.net/lakewoodexcel
is returning 404

2022-01-03 19:05 UTC, skosito commented
> LInk inside .xlsm https://baseledger.net/lakewoodexcel is returning 404

Thanks @fosgate29 great catch
I changed url now to point to README i added here - keep in mind that currently link is not working, it will after merge to master, since link contains branch information.

2022-01-24 15:27 UTC, ognjenkurtic approved these changes

2022-01-27 12:06 UTC, fosgate29 approved these changes

2022-01-27 12:07 UTC, merged