Update TSC Attendance Governance (Do Not Merge)
eea-oasis/baseline pull request #610
Opened 2023-01-05 01:17 UTC by GoldenBit0

Per discussions in recent PGB, TSC, and Core Dev calls, this PR contains the updated TSC attendance governance for review by the PGB.

If the PGB approves, 'Do Not Merge' will be removed and the maintainers can proceed with standard PR approval process.

# Description

Updated TSC attendance governance to include what happens if x meetings are missed, process for removal, etc.

## Related Issue

## Motivation and Context

This change is to improve clarify for TSC attendance policy and process.

## How Has This Been Tested

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Request to be added as a Code Owner/Maintainer

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I commit to abide by the Responsibilities of Code Owners/Maintainers.

2023-01-10 01:36 UTC, tasdienes commented on docs/governance/governance.md
> +If a TSC member does not comply with the attendance policy, a simple majority vote for removal is conducted by Oasis for the remaining TSC members that are not being considered for removal to vote.
Is it necessary for the vote to be "conducted by Oasis"?

2023-01-11 16:52 UTC, Therecanbeonlyone1969 requested changes

2023-01-11 16:52 UTC, Therecanbeonlyone1969 commented on docs/governance/governance.md
> +If a TSC member does not comply with the attendance policy, a simple majority vote for removal is conducted by Oasis for the remaining TSC members that are not being considered for removal to vote.
```suggestion
If a TSC member does not comply with the attendance policy, a simple majority vote of the remaining TSC members that are not being considered for removal is sufficient to remove the TSC member.
```

2023-02-07 21:24 UTC, GoldenBit0 commented
Need to update PR to match voting rights to PGB voting eligibility.

2023-04-12 16:46 UTC, GoldenBit0 commented
4/12/23 PGB Call: Simple majority unanimous approval for the updated TSC governance.

PR is ready for review/merge.

2023-04-12 18:28 UTC, Therecanbeonlyone1969 approved these changes
LGTM

2023-04-12 19:17 UTC, ognjenkurtic approved these changes

2023-04-12 19:17 UTC, merged