Issue #651 - Add Ryan to codeowners, update maintainers
eea-oasis/baseline pull request #652
Opened 2023-02-20 18:25 UTC by fleischr

# Description

Adds Ryan as a Baseline codeowner
Adds a link to the codeowners file in the MAINTAINERS doc

## Related Issue

#651 

## Motivation and Context

Ryan to help out with BRI-1 specific topics and cleanup in Baseline repo
Current maintainers file uses an out of date list of maintainers

## How Has This Been Tested

non-breaking change
## Screenshots (if appropriate)

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Request to be added as a Code Owner/Maintainer

## Checklist

- [ ] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ X] I commit to abide by the Responsibilities of Code Owners/Maintainers.

2023-02-20 18:31 UTC, Therecanbeonlyone1969 submitted a review, later dismissed
I am in favor of that.

2023-02-20 21:35 UTC, ognjenkurtic requested changes
I am not in favor. You can help with BRI-1 stuff and cleanup without being a maintainer, and i would like to see more non-vendor contributions before adding someone as a maintainer. Open for discussion.

2023-02-22 05:05 UTC, fleischr commented
Having attended Baseline core devs regularly for nearly a year, studied the BRI-1 implementation both in and outside this repo extensively, and the developer outreach duties I perform in my current role, I do believe I have demonstrated the qualifying knowledge and dedication needed to be a maintainer. Consider too my hands-on experience in SAP development particularly in applying Baseline as a value-added POV. Additionally - there will likely be some repo activities in the future that benefit from ongoing coordination between Baseline and PRVD that I'll be glad to assist with.

2023-02-22 10:59 UTC, skosito commented
> Having attended Baseline core devs regularly for nearly a year, studied the BRI-1 implementation both in and outside this repo extensively, and the developer outreach duties I perform in my current role, I do believe I have demonstrated the qualifying knowledge and dedication needed to be a maintainer. Consider too my hands-on experience in SAP development particularly in applying Baseline as a value-added POV. Additionally - there will likely be some repo activities in the future that benefit from ongoing coordination between Baseline and PRVD that I'll be glad to assist with.

My point is, how could someone with 0 commits and technical contributions be a maintainer of this or any repo? I keep saying this repo, because in this context any other repo is irrelevant. There are so many opportunities to do actual technical contributions here, for example, bri-1 test suite which is not working for years, and it is inside this repo here. Instead of keep announcing contributions, I think you should just do them. All of current maintainers completed some grant work and led couple implementation efforts where this open source project benefited, before applying or being proposed to become maintainer.

But, this is just my opinion, and won't go into more details, I just checked, you only need 2 votes for this, not all 8.

2023-04-16 19:28 UTC, Manik-Jain approved these changes

2023-04-16 19:30 UTC, Manik-Jain requested changes
waiting for the discussion points to be addressed

2023-05-07 02:25 UTC, fleischr commented
I've withdrawn my application to be added to codeowners at this time. I have kept some edits in another file removing some out of date references to codeowners.

2023-05-07 02:27 UTC, fleischr commented
@Manik-Jain @skosito @ognjenkurtic FYI.

2023-05-08 19:32 UTC, closed without merging