consider case-sensitivity when logging in
eea-oasis/baseline pull request #674
Opened 2023-04-27 16:59 UTC by mkxx712

# Description
Add a small function to avoid failure when logging in.

## Related Issue
#671 

## Motivation and Context
With no idea that I need to change all my address character into all upper/lower case, I fail to log in.

## How Has This Been Tested
Use an address contains both upper and lower address and can log in successfully.

## Screenshots (if appropriate)
<img width="639" alt="image" src="https://user-images.githubusercontent.com/122747873/234934865-fb6251d9-3c06-41c5-bb59-06d6f5f2c6d4.png">

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Request to be added as a Code Owner/Maintainer

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I commit to abide by the Responsibilities of Code Owners/Maintainers.

2023-05-01 15:49 UTC, Kasshern requested changes

2023-05-02 02:43 UTC, Manik-Jain commented on examples/bri-3/src/bri/auth/agent/auth.agent.ts
> +    const isValid = publicKeyFromSignature.toLowerCase() === senderPublicKey;
when web3 library reads current MM address, the default is lowercase.

2023-05-02 02:43 UTC, Manik-Jain submitted a review, later dismissed

2023-05-04 13:45 UTC, ognjenkurtic commented on examples/bri-3/src/bri/auth/agent/auth.agent.ts
> +    const isValid = publicKeyFromSignature.toLowerCase() === senderPublicKey;
+1 for lowercase on both sides. We are not using this code only for logging in, and public key is an input that is coming from the outiside so we do not have any control over its format

2023-05-10 20:14 UTC, Kasshern commented on examples/bri-3/src/bri/auth/agent/auth.agent.ts
> +    const isValid = publicKeyFromSignature.toLowerCase() === senderPublicKey;
@mkxx712  Please fix and request approval again

2023-05-10 20:17 UTC, mkxx712 commented on examples/bri-3/src/bri/auth/agent/auth.agent.ts
> +    const isValid = publicKeyFromSignature.toLowerCase() === senderPublicKey;
Thanks for all the comments!

2023-05-11 14:16 UTC, Kasshern submitted a review, later dismissed

2023-05-11 20:33 UTC, ognjenkurtic commented on examples/bri-3/src/bri/auth/agent/auth.agent.ts
> +    const isValid = publicKeyFromSignature.toLowerCase() === senderPublicKey;
Please run prettier and we can merge

2023-05-11 20:59 UTC, mkxx712 commented on examples/bri-3/src/bri/auth/agent/auth.agent.ts
> +    const isValid = publicKeyFromSignature.toLowerCase() === senderPublicKey;
@ognjenkurtic Done (Sorry about that!

2023-05-11 23:10 UTC, Manik-Jain approved these changes

2023-05-13 21:04 UTC, merged